language: ruby

rvm: 2.1.2

bundler_args: --binstubs --jobs=3 --retry=3 --deployment

sudo: false

cache: bundler

before_script:
  - psql -c 'create database "bundler-api";' -U postgres
  - ./script/setup --verbose

script: rspec

notifications:
  campfire:
    on_success: changed
    on_failure: always
    rooms:
      - secure: "B4ev1d4ZH0Xro49xIunvZNAF2LR0hDgvfpzYMcqUlLNtY5YSmUHbyroVU60w\n10pgYkEhH3DXzHGSYLoYlxGC7foFCZhTkf9JaNgIoSnQmFet+7C66wEkskoY\nwa9n1V3WGic5ZFVBnrZ1IFM6D3hLlAfQdwnwC5GWSrSS9B0jjdI="
